[project]
name = "tracklab"
version = "1.3.23"
description = "A Modular End-to-End Tracking Framework for Research and Development"
readme = "README.md"
authors = [
    { name = "Victor Joos", email = "victorjoosdtb@gmail.com" },
    { name = "Baptiste Standaert", email = "baptiste.standaert@uclouvain.be"},
    { name = "Vladimir Somers", email = "vladimir.somers@uclouvain.be"},
]

requires-python = ">=3.9"
dependencies = [
    "hydra-core",
    "lightning",
    "pytorch_lightning",
    "numpy<2.0",
    "ultralytics",
    "filterpy",
    "torch==1.13.1",
    "torchvision",
    "soccernet==0.1.55",
    "yt-dlp",
    "gdown",
    "pandas",
    "matplotlib",
    "rich",
    "tabulate",
    "sn-trackeval",
    "lap",
    "distinctipy",
    "rtmlib",
    "transformers",
    "accelerate",
    "huggingface-hub",
    "opencv-python",
    "tqdm",
    "omegaconf",
    "requests",
    "wandb",
    "scipy",
    "yacs",
    "scikit-image",
    "torchreid",
    "tensorboard",
    "prtreid",
    "calibration",
    "mmocr==1.0.1",
    "lightning==2.0.9",
    "easyocr==1.7.1",
    "mmdet~=3.1.0",
    "openmim==0.3.9",
]

[dependency-groups]
dev = [
    "tracklab",
    "sphinx",
    "sphinx_rtd_theme",
    "myst-parser",
]

[project.scripts]
tracklab = "tracklab.main:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [".", "plugins/track"]
include = ["tracklab*", "bot_sort*", "bpbreid_strong_sort*", "byte_track*",
    "deep_oc_sort*", "oc_sort*", "strong_sort*", "hydra_plugins.*"]
exclude = []

[tool.setuptools.package-data]
"*" = ["*.txt", "*.rst", "*.yaml"]

[tool.uv]
no-build-isolation-package = ["chumpy"]

[tool.uv.sources]
prtreid = { git = "https://github.com/VlSomers/prtreid.git" }
torchreid = { git = "https://github.com/VlSomers/bpbreid" }
calibration = { workspace = true, editable = true }

[tool.uv.workspace]
members = [
    "plugins/calibration",
]
