# Chelsea Detector Test Config

# Experiment name
experiment_name: "chelsea_detector_test"

# Path definitions
home_dir: "${oc.env:HOME}"
data_dir: "${project_dir}/data"
model_dir: "${project_dir}/pretrained_models"

defaults:
  - dataset: video
  - engine: offline
  - callbacks/export_callback: gs
  - callbacks/visualization_callback: bbox
  - pipeline/bbox_detector: yolo_ultralytics_11_soccernet_finetune
  - _self_

pipeline_order:
  - bbox_detector

dataset:
  video_path: ${data_dir}/SoccerNet/england_epl/2014-2015/2015-02-21 - 18-00 Chelsea 1 - 1 Burnley/1_720p.mkv
  nvid: 1
  nframes: 200

num_cores: 16
use_wandb: False
use_rich: True
infer_tracking: True
print_config: False

callbacks:
  export_callback:
    save_path: "exports"
  visualization_callback:
    save_images: True
    visualizers:
      detections:
        _target_: tracklab.callbacks.visualization_callback.DefaultDetection
      balls:
        _target_: tracklab.callbacks.visualization_callback.BallCircle
        print_id: True
        print_confidence: True
        circle_color: [255, 255, 0]  # Bright yellow in BGR
        circle_thickness: 5

state:
  save_file: "states/${experiment_name}.pklz"
  load_file: null

pipeline:
  bbox_detector:
    cfg:
      min_confidence: 0.1
     

project_dir: "${hydra:runtime.cwd}"
hydra:
  output_subdir: "configs"
  job:
    chdir: True
  run:
    dir: "outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"