# TrackLab config

# The defaults list contains the files that will be used
# to create the final config file. This item *must* be
# the first element in the file.
defaults:
  - dataset: video  # Back to video dataset
  # - eval: trackeval
  - engine: offline
  - callbacks/visualization_callback: bbox
  - pipeline/bbox_detector: yolo_ultralytics
  - pipeline/pose_estimator: yolo_ultralytics-pose
  - pipeline/reid: kpr
  - pipeline/track: oc_sort
  - _self_

# Module order definition:
# - Defines the order in which the modules will be called
# - If loading a tracking state from disk, remove modules whose outputs are already provided in the loaded state
# Use 'module_order: []' for an empty pipeline
module_order:
  - bbox_detector
  #- pose_estimator
  #- reid
  #- track

num_cores: 4

# Logging
experiment_name: "tracklab"
print_config: false
use_wandb: false

# Paths
data_dir: "${project_dir}/data"
model_dir: "${project_dir}/pretrained_models"

# State files loading/saving
state:
  load_file: null
  save_file: "${project_dir}/states/${experiment_name}.pklz"
  load_from_public_dets: false
  load_from_groundtruth: false

# Flag parameters
infer_tracking: true   # Enable tracking operation (includes detection)
use_rich: true

# Callback configuration overrides
callbacks:
  eval_callback:

# configure Hydra to use the current working directory
# and set up the output directory according to experiment_name
project_dir: "${hydra:runtime.cwd}"
hydra:
  job:
    chdir: True
  run:
    dir: "outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"