defaults:
  - colors_gs # For team-specific color tuning

_target_: tracklab.callbacks.VisualizationCallback
save_videos: False
save_gifs:   False
save_images: False
save_dir: "visualization"

visualizers:
  frame_counter:
    _target_: tracklab.callbacks.visualization_callback.FrameCount
  pitch:
    _target_: tracklab.callbacks.visualization_callback.pitch.Pitch
  players:
    _target_: tracklab.callbacks.visualization_callback.players.CompletePlayerEllipse
  ball:
    _target_: tracklab.callbacks.visualization_callback.ball.BallCircle
  radar:
    _target_: tracklab.callbacks.visualization_callback.pitch.Radar


# Color settings for visualization.
colors:
  # Choose the color to display:
  # - null: No display.
  # - RGB code: A color in [R, G, B] format.
  # - team: A color based on the assigned team (left or right - can be modified in colors_gs file).
  # - track_id: A color based on the tracking ID (for prediction or ground_truth only).
  default:
    no_id: [0, 255, 255]  # Yellow (BGR) for objects with no ID (e.g., balls without tracking).
    prediction: "team"  # Color setting for tracked predictions, based on team.
    ground_truth: null  # Color setting for ground truth, specified as an RGB value.
  # Estimated number of objects to track to generate colors that are visually
  # distinct from one another when using "track_id" or colormap name.
  cmap: 22
