# YOLO Ultralytics configuration optimized for SoccerNet fine-tuning
# Target classes: ball, goalkeeper, other, player, referee

_target_: tracklab.pipeline.bbox_detector.yolo_ultralytics_api.YOLOUltralytics
batch_size: 16
training_enabled: True  # Enable training
cfg:
  # Dataset name for model naming
  dataset_name: "soccernet"
  
  # Dataset split names for SoccerNet (uses standard names)
  # split_names:
  #   train: "train"
  #   val: "val"
  #   eval: "eval"
  #   test: "test"
  
  # Start with medium pretrained model for better performance
  path_to_checkpoint: "${model_dir}/yolo/yolo11m.pt"

  # Detection threshold
  min_confidence: 0.3

  # Class mapping for SoccerNet dataset
  # SoccerNet categories: ball(4), goalkeeper(2), other(7), player(1), referee(3)
  # Map to YOLO classes: ball(0), goalkeeper(1), other(2), player(3), referee(4)
  class_mapping:
    names:
      0: "ball"
      1: "goalkeeper"
      2: "other"
      3: "player"
      4: "referee"
    source_to_yolo:
      4: 0  # SoccerNet ball -> YOLO class 0
      2: 1  # SoccerNet goalkeeper -> YOLO class 1
      7: 2  # SoccerNet other -> YOLO class 2
      1: 3  # SoccerNet player -> YOLO class 3
      3: 4  # SoccerNet referee -> YOLO class 4
    yolo_to_source:
      0: 4  # YOLO class 0 -> SoccerNet ball
      1: 2  # YOLO class 1 -> SoccerNet goalkeeper
      2: 7  # YOLO class 2 -> SoccerNet other
      3: 1  # YOLO class 3 -> SoccerNet player
      4: 3  # YOLO class 4 -> SoccerNet referee

  # Training configuration optimized for SoccerNet fine-tuning
  training:
    epochs: 50  # Fine-tuning with 50 epochs for soccer domain
    batch_size: 16  # Good balance of speed and performance
    img_size: 640
    data_path: null  # Will be auto-generated from SoccerNet dataset
    
    # Optimizer settings for fine-tuning
    optimizer: SGD
    lr0: 0.001  # Lower learning rate for fine-tuning
    lrf: 0.1    # Final learning rate factor
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    
    # Freeze settings for transfer learning
    freeze: 10  # Freeze backbone for first 10 epochs
    
    # Data augmentation (moderate for fine-tuning)
    augmentation:
      hsv_h: 0.015    # Hue augmentation
      hsv_s: 0.7      # Saturation augmentation
      hsv_v: 0.4      # Value augmentation
      degrees: 0.0    # No rotation (soccer field is always oriented)
      translate: 0.1  # Small translation
      scale: 0.5      # Scale augmentation
      shear: 0.0      # No shear
      perspective: 0.0 # No perspective
      flipud: 0.0     # No vertical flip (gravity matters)
      fliplr: 0.5     # 50% horizontal flip (soccer is symmetric)
      mosaic: 1.0     # Full mosaic augmentation
      mixup: 0.0      # No mixup
      copy_paste: 0.0 # No copy-paste
    
    # Training efficiency
    amp: true        # Automatic Mixed Precision for faster training
    cache: false     # Disable caching to save memory
    device: ""       # Auto-detect GPU/CPU
    workers: 8       # Number of dataloader workers
    
    # Validation settings
    val: true        # Enable validation during training
    save_period: 10  # Save checkpoint every 10 epochs
    patience: 10     # Early stopping patience
    
    # Output settings
    plots: true      # Generate training plots
    verbose: true    # Verbose logging