_target_: tracklab.pipeline.bbox_detector.yolo_ultralytics_api.YOLOUltralytics

# Offline / high-accuracy preset for football (soccer) games
# Follows same `cfg:` structure as `yolo_ultralytics_soccernet.yaml` so the wrapper
# receives expected keys like `path_to_checkpoint` and `training`.
batch_size: 8
training_enabled: True
cfg:
  # Path to pretrained checkpoint (can be local model_dir or a full path)
  path_to_checkpoint: "${model_dir}/yolo/yolo11m.pt"
  # Low-level default if no path provided by the user
  default_model: "yolo11m.pt"

    # Save path for trained model
  save_path: "${project_dir}/pretrained_models/yolo/yolo11m_finetuned_soccernet.pt"

  # Detector-level minimum confidence used by the wrapper
  min_confidence: 0.18

  # Model-specific runtime settings (used by helper scripts / upstream wrappers)
  model:
    model_name: "yolo11x.pt"
    imgsz: 640
    conf: 0.20
    iou: 0.60
    max_det: 2000
    half: True
    batch_size: 8

  # Optional offline-only hints (not strictly required by the YOLO API)
  tta: ["horizontal_flip"]
  postproc:
    soft_nms: True
    size_filter_min_area_ratio: 0.0008

 
  training:
    # Training tuned for a single RTX 4090. Adjust `img_size` and `batch_size` if you
    # require different memory/speed trade-offs.

    epochs: 50
    batch_size: 8        # batch size per GPU (for imgsz 1280 reduce to 2 or use accumulation)
    accumulate: 2        # New: gradient accumulation for effective larger batch
    img_size: 640        # train at 640 for stable/faster training, fine-tune at 1280 if needed
    data_path: null      # set to your dataset path or leave as TrackingDataset input

    # Optimizer and lr schedule
    optimizer: AdamW
    lr0: 0.00005         # Lower initial learning rate
    lrf: 0.01
    momentum: 0.9
    weight_decay: 0.002  # Increased weight decay for stronger regularization

    # Augmentation (stronger to handle poor-quality video)
    augmentation:
      hsv_h: 0.02
      hsv_s: 0.8
      hsv_v: 0.5
      degrees: 7.0
      translate: 0.12
      scale: 0.6
      shear: 2.0
      perspective: 0.001
      flipud: 0.1
      fliplr: 0.5
      mosaic: 0.7
      mixup: 0.2
      copy_paste: 0.1

    # Standard training settings
    amp: True
    cache: True         # Changed: enable data caching for faster loading
    device: ""
    workers: 32         # Increased: more data loading workers
    val: True
    save_period: 2    # Increased: save checkpoints less frequently
    patience: 10       # Increased patience for more tolerance to val fluctuations
    plots: True
    verbose: True
