# Simple YOLO Ultralytics configuration that works with ANY TrackLab dataset
# Automatically adapts to dataset categories and optimizes training

_target_: tracklab.pipeline.bbox_detector.yolo_ultralytics_api.YOLOUltralytics
batch_size: 16
training_enabled: True
cfg:

  # Use appropriate pretrained model based on dataset
  path_to_checkpoint: "${model_dir}/yolo/yolo11x.pt"
  # Save path for trained model
  save_path: "${project_dir}/pretrained_models/yolo/yolo11x_finetuned_soccernet.pt"

  # Detection confidence threshold
  min_confidence: 0.3

  training:
    epochs: 50
    batch_size: 16
    img_size: 640
    data_path: null

    # Smart optimizer selection
    optimizer: AdamW
    lr0: 0.0001
    lrf: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    warmup_epochs: 3
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
   

    # Adaptive freezing based on dataset complexity
    freeze: 10
    
    # Conservative augmentation that works for all datasets
    augmentation:
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      degrees: 0.0
      translate: 0.1
      scale: 0.5
      shear: 0.0
      perspective: 0.0
      flipud: 0.0
      fliplr: 0.5
      mosaic: 1.0
      mixup: 0.0
      copy_paste: 0.0

    # Standard training settings
    amp: true
    cache: false
    device: ""
    workers: 8
    val: true
    save_period: 5
    patience: 10
    plots: true
    verbose: true
