_target_: tracklab.engine.OfflineTrackingEngine

num_workers: ${num_cores}
callbacks:
  progress:
    _target_: tracklab.callbacks.Progressbar
    use_rich: ${use_rich}
  vis: ${callbacks.visualization_callback}
  export: ${callbacks.export_callback}
  eval: ${callbacks.eval_callback}
