_target_: tracklab.callbacks.ExporterCallback
exporter:
  _target_: tracklab.callbacks.GSExporter
save_path: "exports"
export_per_video: false
bbox_column: "bbox_ltwh"
save_classes: false
is_ground_truth: false
